### ISSUE TITLE
ltx file format extensibility (faster encryption + faster hashing + faster compression)

### ISSUE THREAD

**Issue by sylvain101010** [superfly/ltx#55]
Hi there,

I really like your work around SQLite!

I maintain some benchmark for Go (https://github.com/skerkour/go-benchmarks) and it appears that the selected algorithms are not the fastest, so I was wondering to what extent the `ltx` file format will be able to evolve to accommodate faster algorithms in the future?

For example, the hashing function `blake3` or the checksum function `xxh3` are both way faster than `crc64` and `snappy` is generally faster than `lz4`. 

Also, I'm not sure to understand if the current format supports encryption? Can you please enlighten me on this point.

Thank you!

**Comment by benbjohnson** [comment]
> I was wondering to what extent the ltx file format will be able to evolve to accommodate faster algorithms in the future?

The compression algorithm could change in the future as it's just a flag on the file. The checksumming would be tougher to switch out.

> For example, the hashing function blake3 or the checksum function xxh3 are both way faster than crc64 and snappy is generally faster than lz4.

We're not generally limited by compression or checksumming in our performance. LZ4 was chosen because of fast decompression speeds, reasonable compression speed, and the available cross-language tooling around it. CRC64 was chosen as it was already in the standard library and performed fast enough for what we need.
